### PR TITLE
Update TileObjectData.cs

### PR DESCRIPTION
**Pull request by tysonstrange**
Fixes https://github.com/NyxStudios/TerrariaAPI-Server/issues/37

### CODE REVIEW

**Comment by QuiCM** [comment]
cc @tylerjwatson @nicatronTg @Enerdy @Ijwu 
Looks fine, please provide input

**Comment by tysonstrange** [comment]
I'm running this build atm. haven't noticed any other issues..

The only issue is... https://github.com/NyxStudios/TerrariaAPI-Server/issues/43

:)

**Comment by hakusaro** [comment]
@NyxStudios/tshock I'm good with this getting merged.

**Comment by tysonstrange** [comment]
Hoping for it asap... coz all my traps are broken right now. :D

**Comment by tysonstrange** [comment]
Can I get someone to build for me :3

**Pull request merged**
