### PR TITLE
Update to 1.3.3.3

### PR DESCRIPTION
**Pull request by Simon311**

### CODE REVIEW

**Comment by AxisKriel** [comment]
Oh yeah this happened.

Will review shortly.

On 3 Oct 2016, at 21:49, Simon <notifications@github.com<mailto:notifications@github.com>> wrote:

---

You can view, comment on, or merge this pull request online at:

  https://github.com/NyxStudios/TerrariaAPI-Server/pull/100

Commit Summary
-   Update to Terraria 1.3.3.3
-   Update AssemblyInfo.cs

File Changes
-   M Properties/AssemblyInfo.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-0 (4)
-   M Terraria/GameContent/Achievements/CustomFlagCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-1 (2)
-   M Terraria/GameContent/Achievements/CustomFloatCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-2 (2)
-   M Terraria/GameContent/Achievements/CustomIntCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-3 (2)
-   M Terraria/GameContent/Achievements/ItemPickupCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-4 (2)
-   M Terraria/GameContent/Achievements/NPCKilledCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-5 (2)
-   M Terraria/GameContent/Achievements/ProgressionEventCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-6 (2)
-   M Terraria/GameContent/Achievements/TileDestroyedCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-7 (2)
-   M Terraria/GameContent/Biomes/CampsiteBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-8 (2)
-   M Terraria/GameContent/Biomes/CaveHouseBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-9 (2)
-   M Terraria/GameContent/Biomes/CorruptionPitBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-10 (2)
-   M Terraria/GameContent/Biomes/DesertBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-11 (2)
-   M Terraria/GameContent/Biomes/EnchantedSwordBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-12 (2)
-   M Terraria/GameContent/Biomes/GraniteBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-13 (2)
-   M Terraria/GameContent/Biomes/HiveBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-14 (2)
-   M Terraria/GameContent/Biomes/HoneyPatchBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-15 (2)
-   M Terraria/GameContent/Biomes/MahoganyTreeBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-16 (2)
-   M Terraria/GameContent/Biomes/MarbleBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-17 (2)
-   M Terraria/GameContent/Biomes/MiningExplosivesBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-18 (2)
-   M Terraria/GameContent/Biomes/ThinIceBiome.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-19 (2)
-   M Terraria/GameContent/Events/BirthdayParty.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-20 (2)
-   M Terraria/GameContent/Events/CultistRitual.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-21 (2)
-   M Terraria/GameContent/Events/ScreenDarkness.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-22 (2)
-   M Terraria/GameContent/Events/ScreenObstruction.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-23 (2)
-   M Terraria/GameContent/Generation/ActionGrass.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-24 (2)
-   M Terraria/GameContent/Generation/ActionPlaceStatue.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-25 (2)
-   M Terraria/GameContent/Generation/ActionStalagtite.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-26 (2)
-   M Terraria/GameContent/Generation/ActionVines.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-27 (2)
-   M Terraria/GameContent/Generation/PassLegacy.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-28 (2)
-   M Terraria/GameContent/Generation/ShapeBranch.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-29 (2)
-   M Terraria/GameContent/Generation/ShapeFloodFill.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-30 (2)
-   M Terraria/GameContent/Generation/ShapeRoot.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-31 (2)
-   M Terraria/GameContent/Generation/ShapeRunner.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-32 (2)
-   M Terraria/GameContent/Generation/TrackGenerator.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-33 (2)
-   M Terraria/GameContent/Generation/WorldGenLegacyMethod.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-34 (2)
-   M Terraria/GameContent/NetModules/NetLiquidModule.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-35 (2)
-   M Terraria/GameContent/UI/WiresUI.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-36 (2)
-   M Terraria/ID/RecipeGroupID.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-37 (2)
-   M Terraria/Initializers/AchievementInitializer.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-38 (2)
-   M Terraria/Initializers/ChatInitializer.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-39 (2)
-   M Terraria/Initializers/DyeInitializer.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-40 (2)
-   M Terraria/Initializers/NetworkInitializer.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-41 (2)
-   M Terraria/Initializers/PlayerDataInitializer.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-42 (2)
-   M Terraria/Initializers/ScreenEffectInitializer.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-43 (2)
-   M Terraria/Main.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-44 (6)
-   M Terraria/Net/NetManager.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-45 (2)
-   M Terraria/Utilities/WeightedRandom.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-46 (2)
-   M Terraria/World.Generation/Actions.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-47 (2)
-   M Terraria/World.Generation/BiomeCollection.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-48 (2)
-   M Terraria/World.Generation/Conditions.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-49 (2)
-   M Terraria/World.Generation/GenAction.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-50 (2)
-   M Terraria/World.Generation/GenCondition.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-51 (2)
-   M Terraria/World.Generation/GenModShape.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-52 (2)
-   M Terraria/World.Generation/GenPass.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-53 (2)
-   M Terraria/World.Generation/GenSearch.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-54 (2)
-   M Terraria/World.Generation/GenShape.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-55 (2)
-   M Terraria/World.Generation/ModShapes.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-56 (2)
-   M Terraria/World.Generation/Modifiers.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-57 (2)
-   M Terraria/World.Generation/Passes.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-58 (2)
-   M Terraria/World.Generation/Searches.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-59 (2)
-   M Terraria/World.Generation/ShapeData.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-60 (2)
-   M Terraria/World.Generation/Shapes.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-61 (2)
-   M Terraria/World.Generation/SimpleStructure.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-62 (2)
-   M Terraria/World.Generation/WorldGenerator.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-63 (2)
-   M Terraria/World.Generation/WorldUtils.cshttps://github.com/NyxStudios/TerrariaAPI-Server/pull/100/files#diff-64 (2)

Patch Links:
-   https://github.com/NyxStudios/TerrariaAPI-Server/pull/100.patch
-   https://github.com/NyxStudios/TerrariaAPI-Server/pull/100.diff

##

**Comment by Patrikkk-zz** [comment]
lgtm :+1: 
Did you build and run it, connect with client? (With TShock too)

**Comment by Simon311** [comment]
Yes, @Patrikkk, playing right now

**Comment by AxisKriel** [comment]
Wtf is this update.

:+1:...

**Review by hakusaro — APPROVED** [review]
lgtm

**Pull request merged**
