### PR TITLE
Add missing updated NPC class code

### PR DESCRIPTION
**Pull request by Patrikkk-zz**
Add missing updated NPC class code

### CODE REVIEW

**Comment by Ijwu** [comment]
Is this directly solving an issue? Can we say this missing code was the cause of the NPCs skipping around?

**Comment by Patrikkk-zz** [comment]
I cannot confirm. Most of this is position related code. 
Quoting White:

> There's possibly something on the server end that isn't updating positions and velocities correctly which could worsen the issue
> I.e. clients believe NPC is at position (x, y) because they try to predict, but server thinks its at (x2, y2) so you get a desync and skipping

Only case this can happen is either decomplilation issues, or our code is not up to date properly.
So I diffed AI class to see if it's up to date properly. And these were missing from our code. 

Not sure how to test this my self because I couldn't re-produce the skipping locally. (Although I did experience it previously).

**Comment by MarioE** [comment]
Most of this is probably AI-specific. Even if it doesn't fix the skipping, it should still be included.

**Comment by Patrikkk-zz** [comment]
What MarioE said. Skipping happens for every NPCs.
In my update they _are_ npc/AI specific. These bits of code only get hit at certain NPCs or AIs.

**Comment by Ijwu** [comment]
Alright, just trying to pinpoint if this is something we missed or a definitive solution to an issue. 

LGTM

**Comment by Patrikkk-zz** [comment]
Sure :)
To give more info, these changes are inside:
aiStyle 1, 6, 27, 44, 54, 76 ,80
and npc type 392

**Pull request merged**
