### PR TITLE
Add compatibility for Terraria 1.3.5.x

### PR DESCRIPTION
**Pull request by hakusaro**
This is the accompanying PR in the API for https://github.com/NyxStudios/TShock/pull/1423.

Issues that still need to be done:

- [x] `PacketTypes.ChatText` needs to be deprecated.
- [x] `InvokeServerBroadcast` needs to be called on packet 82/needs to reflect that ChatText doesn't fire or this event will never fire.
- [ ] Backwards compatibility for the new command system needs to be added. In T1.3.5, `/me` is implemented by default which means that TShock/other handlers need to work around it (bad).
- [x] Changelog has been updated to add the OnNpcKilled hook

### CODE REVIEW

**Comment by hakusaro** [comment]
Just as a slight update on this: Since last night, @tylerjwatson and @DeathCradle worked to update OTAPI to add a new broadcast hook, which, when implemented in TShock, will let people block boss messages and the like before serialization (meaning faster and more performant than blocking it later in the chain). This means that TSAPI needs to be updated to support these hooks, but we're making progress.

**Comment by tylerjwatson** [comment]
This has been completed as of NyxStudios/TerrariaAPI-Server@3b96d98.  Server broadcast messages are sent to the existing ServerBroadcast TSAPI hook.

**Comment by hakusaro** [comment]
@tylerjwatson unfortunately that commit you linked to was made in January and the current api doesn't call InvokeServerBroadcast anywhere

**Comment by Ijwu** [comment]
What is keeping us from a 1.3.5 release at current time?

**Comment by hakusaro** [comment]
White.

**Pull request merged**
