### PR TITLE
Added Evil Type option during world creation

### LINKED ISSUE #63: Allow specification of crimson/corruption in world generation
Small QoL improvement

### PR DESCRIPTION
**Pull request by NoNiMad**
Added the possibility to choose which Evil Type you want during World Creation, like it's now possible in the 1.3.2 client. Fix #63 

Not a big thing, but it's an occasion for me to contribute to this awesome project I've just discovered and to thank you for your hard work!

### CODE REVIEW

**Comment by Patrikkk-zz** [comment]
Awesome :) 
I know my word is not official, but lgtm :+1: 
Did you write this code by your self? I see it differs from the source we got from decompiler, but it does the exact same thing.
Only thing is that officially the options are:
1) Random
2) Corrupt
3) Crimtane
No clue why. 
But I kinda prefer the options in your PR. 
Thanks for contributing! ^^

**Comment by NoNiMad** [comment]
Yup, wrote it myself after looking at the similar parts in the existing code. As I am mainly a JavaScript and Java developer, C# is kind of something new to me and I didn't even thought of decompiling!
For the options name, I just copied those in the client in the order they were. Allowed me to use the modulo trick which is better in my opinion than many if (and still extendable).

Happy to contribute!

**Comment by QuiCM** [comment]
:+1:

**Comment by AxisKriel** [comment]
Thank you for your contribution!

**Pull request merged**
