### PR TITLE
Fix NPC's they are not spawning?

### PR DESCRIPTION
**Pull request by rickojp**
Try fix this #118, tested in localhost and monsters spawn properly.

### CODE REVIEW

**Comment by AxisKriel** [comment]
Could you double check your tab settings? I believe you accidentally replaced tabs with spaces on the file.

**Comment by rickojp** [comment]
I do not really know why my Visual Studio insists on break the tabs, could you correct it for me? D;

**Comment by ivanbiljan** [comment]
Just change the setting and format it. I can't even see what was fixed here.

**Comment by Zaicon** [comment]
Rickoo made two changes:
public bool[] buffImmune = new bool[206]; -> public bool[] buffImmune = new bool[Main.maxBuffTypes];
public static int[] killCount = new int[580]; -> public static int[] killCount = new int[Main.maxNPCTypes];

I'll check real quick, but I'm fairly sure that this (alone) isn't going to solve the issue.

**Comment by rickojp** [comment]
I do not know what the problem is with my Visual Studio, the last change I made with Notepad++.
When trying to fix the tab, unwittingly reversing the changes, not funny!
Sorry for the inconvenience, this pull is meant to fix this #118.

**Comment by ivanbiljan** [comment]
@Rickoo You have to explain what you did here. I don't have time for checking what really was fixed.

**Comment by rickojp** [comment]
@ProfessorXZ , 

@Zaicon already corrected this with the pull #120.

**Pull request closed without merging**
