### PR TITLE
Fix empty UUID. Fix invalid UUID

### PR DESCRIPTION
**Pull request by Patrikkk-zz**
There was an exception from empty UUID. (`new byte[0 - 5]` )
Length == 38 makes sure the UUID is proper length. 
Length is _always_ 38 at UUID packet. Not sure why.. since a UUID is 36 characters, thus the `length - 2`.
Since I already have a check on length, The Guid.TryParse  only makes sure the UUID is the correct format: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

If the UUID is invalid, it gives an empty UUID because I want to remove kickEmptyUUID from tshock. config and always kick empty UUID.

### CODE REVIEW

**Comment by QuiCM** [comment]
Now would be a great time to comment that block so that anyone coming across it later on knows what it's doing

**Comment by Patrikkk-zz** [comment]
Added comments

**Comment by QuiCM** [comment]
:+1:

**Comment by Patrikkk-zz** [comment]
:)

**Pull request merged**
