### PR TITLE
Add Wolfje's crash reporter

### PR DESCRIPTION
**Pull request by hakusaro**
This adds Wolfje's crash reporter. @tylerjwatson wrote the code, but I'd like full vetting before merge. Currently blocks #31.

### CODE REVIEW

**Comment by tylerjwatson** [comment]
more work needs to be done, minidumping is only going to work in Windows as mono has no such feature.   This is going to have to be controlled in the dumper

**Comment by hakusaro** [comment]
o

**Comment by tylerjwatson** [comment]
we happy to just have it write dumps to a folder for now?

**Comment by hakusaro** [comment]
@tylerjwatson if it writes dumps to a folder that's definitely good in the department of "if you have a problem please upload this crash." It's a step above nothing right?

**Comment by tylerjwatson** [comment]
I have changes in tshock waiting to be committed for the removal of sensitive information from heapshots but will ruin the CI build as the code references stuff from this branch and not TSAPI's general-devel branch.

The commits are withheld until this is approved, the more testing the better

**Pull request merged**
