### PR TITLE
Rename packet 82 to FingerNetModule.

### LINKED ISSUE #159: Rename packet 82
The name of packet [82] (https://github.com/Pryaxis/TerrariaAPI-Server/blob/28200f7d4447ee275e85856f97eee58fa156ffc4/TerrariaServerAPI/TerrariaApi.Server/PacketTypes.cs#L88) is misleading - it does not cause any netmodule to be loaded, as netmodules are loaded on server startup when `NetManager.Initialize()` is called.  
  
It's an issue rather than PR as we should decide on which name will fit the most, as we'd like to avoid incidents like d8c7be19843605a28d7f643652947f8dd87b9a2d, da8fdeddbd1857e241490c0c310857b9f2371caa and 28200f7d4447ee275e85856f97eee58fa156ffc4 due to poor communication of the change.  
  
I personally opt to rename it to simply NetModule, as that's exactly what it contains. It's a minor change, though.

### PR DESCRIPTION
**Pull request by hakusaro**
Fixes #159

### CODE REVIEW

**Comment by QuiCM** [comment]
Hard pass

**Comment by Ijwu** [comment]
Approved.

**Comment by hakusaro** [comment]
@QuiCM ijwu just approved it

**Comment by QuiCM** [comment]
Hard pass trumps approvals

**Comment by Ijwu** [comment]
hard approval

**Comment by Ijwu** [comment]
what now?

**Pull request closed without merging**
