### PR TITLE
Move argument handling into the API

### PR DESCRIPTION
**Pull request by CJKay**
I have left the -steam argument where it is as, while I presume it serves no function at all and can be deleted, I'll leave that to those who know for certain.

### CODE REVIEW

**Comment by tylerjwatson** [comment]
-1. I have no idea what people's obsession is with handling arguments inside a plugin.  

Exe command line must be handled inside the _exe_. 

Tsapi command line arguments need to be handled inside TSAPI and not a plugin which would make it impossible to control without tshock.

**Comment by hakusaro** [comment]
@tylerjwatson these command line arguments are inside the API, not the TShock plugin

**Comment by CJKay** [comment]
These are TSAPI command line arguments which I have moved into TSAPI. I'm not sure I see where you're coming from. As far as I know, none of these is specific to TShock.

**Comment by tylerjwatson** [comment]
Sorry mate I do applogise. My patch reading skills need work, I was a little jaded after finding someone had moved command line argument handling into TShock library, making it impossible to specify a world path unless tshock was loaded. 

+1

**Comment by CJKay** [comment]
No worries, buddy. Hope this helps.

**Comment by hakusaro** [comment]
No merge until this is resolved. Specifying autocreate and world resulted in this:

**Comment by CJKay** [comment]
I'm unable to reproduce this behaviour.

hmm

hmm2

**Comment by hakusaro** [comment]
Well that sucks, but we're at a standstill until it works on 100% of test cases.

**Comment by hakusaro** [comment]
(I can still reproduce this problem, and I have no clue as to why it happens?)

**Comment by hakusaro** [comment]
Hold on, it's my fault I think. I'll update here in a sec.

**Comment by hakusaro** [comment]
Okay, working now.

**Pull request merged**
