### PR TITLE
Updating to 1.3.1.1

### PR DESCRIPTION
**Pull request by Patrikkk-zz**
Updating to 1.3.1.1

### CODE REVIEW

**Comment by AxisKriel** [comment]
if (tested) :+1:

**Comment by Patrikkk-zz** [comment]
Tested :+1:

**Comment by jackmawer** [comment]
Thank you based Patrikkk.
EDIT: I worked out how to build, and it seems to work <3

**Comment by Ijwu** [comment]
lgtm

**Pull request merged**
