### PR TITLE
Remove UnicodeInput modification and fix path for macOS and Linux

### PR DESCRIPTION
**Pull request by mistzzt**
In Terraria 1.3.5.3, console input has been fixed.
As it would cause console not receiving  some characters, like Chinese characters, the modification should be removed.

The Bootstrapper has some default arguments which are not proper when running on macOS or Linux.

### CODE REVIEW

**Comment by hakusaro** [comment]
I'm gonna go ahead and say that Wolfje needs to comment and verify this is okay. Can you confirm that you tested this with Chinese characters?

**Comment by mistzzt** [comment]
@hakusaro 
I have tested and discussed it in #high-charity with screenshots

**Review by hakusaro — APPROVED** [review]
lgtm_3

**Comment by hakusaro** [comment]
I can confirm that the path issue does create problems on macOS. You get a file named Output\OTAPI.dll but because we don't have a set in stone build procedure for mono, it's easily ignored/overlooked. This should fix that.

**Pull request merged**
