### PR TITLE
Remove support for favorites (and cloud saving)

### PR DESCRIPTION
**Pull request by AxisKriel**
Tested by @chais on Slack, seems to be working. This removes support for World/Character favorites, as those were kind of useless in a Server application.

For those outside of the context, this is a fix for the error people would get if they tried to fire TerrariaServer.exe without having a favorites.json file (possible if they never ran Terraria itself on the server machine).

@NyxStudios/tshock, feel free to add anything. I'm not 100% sure that I removed everything favorite-related, but this works as it is. I will merge this PR whether the [two-man rule](https://en.wikipedia.org/wiki/Two-man_rule) (Two OKs from members with write access) is fulfilled or 7 days have passed; whichever comes first.

### CODE REVIEW

**Comment by hakusaro** [comment]
Sure boss.

**Comment by Ijwu** [comment]
Will review in depth when I'm at a PC. For the record, though, contributing.md states a 7 day timeout on the two man rule. Check your privilege, @enerdy :P

**Comment by AxisKriel** [comment]
Oops, I guess this is what happens when you don't read through everything carefully. Seven days, it is.

**Comment by hakusaro** [comment]
@ijwu but nobody is reading "Pull request acceptance from internal contributors (anyone with write access) requires only one other approval to merge."

**Comment by QuiCM** [comment]
Requesting that you also kill off cloud support while you're at it

**Comment by hakusaro** [comment]
Please kill off cloud support.

**Pull request merged**
