### PR TITLE
Add Evil Type option during world creation

### LINKED ISSUE #1386: Ability to choose between Corruption and Crimson when creating new worlds via TShock
Hi, like the title says, this used to be a feature, but it was lost in recent updates, and I was told to make an issue on here about it so that it might possibly become a feature again, so here I am.

My servers boot up fine on already-created worlds, but if I wanna make a new world and not randomize Crimson/Corruption, I have to do so through the game itself.

### PR DESCRIPTION
**Pull request by mistzzt**
This should fix [#1386][issue]

[issue]: https://github.com/NyxStudios/TShock/issues/1386

### CODE REVIEW

**Review by QuiCM — COMMENTED** [review]
Tagging @DeathCradle to review as he knows how modifications work more than I do

**Review by Ijwu — COMMENTED** [review]
These changes look good. Some confirmation of TerrariaServer IL and googling what OpCodes do seems to confirm that this change will unlock evil world type generation.

I assume this has been tested properly, @mistzzt? I'm going to approve these changes on the basis @DeathCradle gets a peek too.

**Review by Ijwu — APPROVED** [review]

**Comment by hakusaro** [comment]
No go until review by @DeathCradle.

**Comment by mistzzt** [comment]
@Ijwu I have tested and this worked well.

**Comment by SignatureBeef** [comment]
@mistzzt Would there be any reason not to simply set the field `Terraria.Main.SettingsUnlock_WorldEvil` as true on initialise?
While you have plausible modification code, i'm just thinking that if we can avoid a modification it would be the best outcome.

**Comment by mistzzt** [comment]
You're right.
I forgot this...

**Pull request closed without merging**
